### ISSUE TITLE
What is a tar flow?

### ISSUE THREAD

**Issue by oxr463** [geaaru/tar-formers#1]
And why would I need this tool? Are there any alternatives?

**Comment by geaaru** [comment]
What is the reason for this issue? Said me that I need to improve the documentation?
A tar flow is a stream generated by tar protocol.
You can think to it like the stdout of the a command like this:
```shell
$> tar cf - ./mydir 
```
The `stdout` of the tar command is the stream of the protocol used by tar tool to encapsulate the files.

If there are alternatives I leave to you does the check.

The mission is to have a golang library to parse a tar stream and:
- filter files to extract or ignore some files
- rename files at runtime
- (todo) manage the remapping of the uid/gid

The tool is an extra. My first goal is to integrate a golang library to use for the described mission.

The docker archive library does something similar but it's not what i'm searching for.

I'm currently using it to extract files from a docker container and manage the tar flow from `docker export` command.

**Comment by oxr463** [comment]
> What is the reason for this issue? Said me that I need to improve the documentation?

Yeah, basically. I know what a tarball is, but I had never heard of a tar flow. Thank you for explaining it to me!

Perhaps we could amend the README.md file a bit to help potential users understand what problem the software is attempting to solve.

**Comment by geaaru** [comment]
I hope that the README description is sufficient to understand the target. Closing this for now.
